#spring:
#  main:
#    allow-bean-definition-overriding: true
#  application:
#    name: rootapp
#  data:
#    mongodb:
#      uri: mongodb://root:root@db-container:27017/rootdb
#  sql:
#    init:
#      mode: always
#      encoding: UTF-8
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
#
#jwt:
#  secret: kjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmt
#  expiration: 3600

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: test
  data:
    mongodb:
      uri: mongodb://root:root@223.130.142.132:27017/rootdb?authSource=admin&retryWrites=true&w=majority
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  secret: kjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmt
  expiration: 3600
